[project]
name = "agenticdm"
version = "0.1.0"
description = "agenticdm using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "chainlit>=2.9.3",
    "chromadb>=1.1.1",
    "crewai[tools]==1.5.0",
    "langchain>=1.1.2",
    "langchain-chroma>=1.0.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.0",
    "pypdf>=6.3.0",
    "python-dotenv>=1.2.1",
    "sentence-transformers>=5.1.2",
]

[project.scripts]
agenticdm = "agenticdm.main:run"
run_crew = "agenticdm.main:run"
train = "agenticdm.main:train"
replay = "agenticdm.main:replay"
test = "agenticdm.main:test"
run_with_trigger = "agenticdm.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
