from crewai.tools import BaseTool
import json
import os
from typing import Dict, Any, Union, Optional
import logging

STATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../state")

class ReadStateTool(BaseTool):
    name: str = "Read Game State"
    description: str = "Reads the current character sheet or world state. Input 'character' or 'world'."

    def _run(self, file_type: str) -> str:
        try:
            if "char" in file_type.lower():
                filename = "character_sheet.json"
                state_type = "character"

            elif "world" in file_type.lower():
                filename = "world_state.json"
                state_type = "world"

            else:
                return "Invalid file type. Specify 'character' or 'world'."
            
            path = os.path.join(STATE_DIR, filename)
            with open(path, "r") as f:
                data = json.load(f)
            state_str = json.dumps(data, indent=2)

            logging.info(f"Current {state_type} state from ReadStateTool: {state_str}")

            return state_str

        except Exception as e:
            return f"Error reading state: {str(e)}"

from pydantic import BaseModel, Field

class UpdateStateSchema(BaseModel):
    file_type: Optional[str] = Field(default=None, description="The type of file to update ('character' or 'world').")
    updates: Optional[Dict[str, Any]] = Field(default=None, description="Dictionary of fields to update.")
    json_input: Optional[Union[str, Dict[str, Any]]] = Field(default=None, description="Legacy input format (JSON string or dict).")


def _apply_state_updates(current_state: dict, updates: dict, max_recent_events: int = 8) -> dict:
    """
    Helper function to apply state updates generated by the Scribe agent.

    If the Scribe has proposed updates to the world state, this function applies the updates and
    returns an updated world state ensuring that:
    - The "turn_count" field is incremented, even if not explicitly indicated by the Scribe. (FIXME)
    - The "recent_events" list is extended using the new events proposed by the Scribe, if any. The events
        list is then truncated based on `max_recent_events` (default 8).
    """

    # Save original turn count
    if "turn_count" in current_state:
        init_turn_count = current_state["turn_count"]

    for key, value in updates.items():
        # If update is not to "recent_events", apply it directly
        if key != "recent_events":
            current_state[key] = value

        # If update is to "recent_events", ensure Scribe's event updates do not completely overwrite existing
        # recent events (before truncating)
        elif "recent_events" in current_state:
            prev_events = current_state["recent_events"]
            new_events = updates["recent_events"]

            merged_events = [e for e in prev_events]
            seen_events = set([e.lower() for e in prev_events])

            # Append only truly new events (case-insensitive)
            for e in new_events:
                key = e.lower()
                if key not in seen_events:
                    merged_events.append(e)
                    seen_events.add(key)

            # Truncate merged events list if necessary
            if len(merged_events) > max_recent_events:
                merged_events = merged_events[-max_recent_events:]

            # Update recent events
            current_state["recent_events"] = merged_events

    # If updates are to world state and turn count not already incremented, increment it automatically
    if "turn_count" in current_state and current_state["turn_count"] == init_turn_count:
        current_state["turn_count"] = init_turn_count + 1

    return current_state


class UpdateStateTool(BaseTool):
    name: str = "Update Game State"
    description: str = "Updates the game state. Input can be 'file_type' and 'updates' directly, OR a 'json_input' string."
    args_schema: type[BaseModel] = UpdateStateSchema

    def _run(self, file_type: str = None, updates: dict = None, json_input: Union[str, dict] = None) -> str:
        try:
            data = {}
            # 1. Check if arguments are passed directly
            if file_type and updates:
                data = {"file_type": file_type, "updates": updates}
            
            # 2. Check json_input if direct args missing
            elif json_input:
                if isinstance(json_input, dict):
                    data = json_input
                else:
                    try:
                        data = json.loads(json_input)
                    except:
                        import ast
                        try:
                            data = ast.literal_eval(json_input)
                        except:
                            return f"Error parsing input: {json_input}"
            
            # 3. Check for schema hallucination in data
            if "description" in data and "type" in data:
                 desc = data.get("description", "")
                 if "no mechanics" in desc.lower() or "no changes" in desc.lower():
                     return "No changes made."
                 # Try to recover if description IS the json
                 try:
                    data = json.loads(desc)
                 except:
                    pass

            file_type = data.get("file_type") or file_type
            updates = data.get("updates") or updates
            
            if not file_type or not updates:
                return "Missing 'file_type' or 'updates' in input."

            if "char" in file_type.lower():
                filename = "character_sheet.json"
                state_type = "character"

            elif "world" in file_type.lower():
                filename = "world_state.json"
                state_type = "world"

            else:
                return "Invalid file type."
            
            path = os.path.join(STATE_DIR, filename)
            
            with open(path, "r") as f:
                current_state = json.load(f)

            logging.info(f"Current {state_type} state in UpdateStateTool: {json.dumps(current_state, indent=2)}")
            logging.info(f"State updates in UpdateStateTool: {json.dumps(updates, indent=2)}")

            # For nested updates (like stats), the agent should provide the full nested object or we need recursive update.
            # For now, we assume the agent provides the full object for the key they are updating.
            current_state = _apply_state_updates(current_state, updates)
                
            with open(path, "w") as f:
                json.dump(current_state, f, indent=2)

            logging.info(f"Updated {state_type} state from UpdateStateTool: {json.dumps(current_state, indent=2)}")
                
            return f"Updated {filename} successfully."
        except Exception as e:
            return f"Error updating state: {str(e)}"
